### PR TITLE
chore: Update Dockerfile to use crystal 1.12.1

### PR DESCRIPTION
**Pull request by miry**
Update Dockerfile to have latest crystal and minor changes.

### CODE REVIEW

**Review by jgaskins — APPROVED** [review]
Thanks! This is one of the hard parts about upgrading Crystal. 😄 I've thought about using `latest-alpine`, but then the container images break randomly and it's hard to know which version of Crystal a given image is built against.

**Comment by miry** [comment]
@jgaskins I can add github action with dependa bot, like "we" like :)

**Comment by jgaskins** [comment]
lol Does Dependabot track container dependencies?

**Comment by miry** [comment]
Yep, for sure it can upgrade FROM, 
but also if I am not wrong, it could upgrade specific version of package if it was specified explictly.

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems

Example: https://github.com/opentracing-contrib/nginx-opentracing/pull/605

**Comment by jgaskins** [comment]
TIL!

**Pull request merged**
